version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: luminex-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: luminex_plant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - luminex-network

  redis:
    image: redis:7-alpine
    container_name: luminex-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - luminex-network
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:

networks:
  luminex-network:
    driver: bridge
